name: Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
        submodules.recursive: true

    - name: List directories
      run: ls -alh  # 디렉토리 구조 확인

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --source fpexample --destination fpexample/public  # fpexample 하위에 public 생성

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # 개인 토큰 그대로 유지
        publish_dir: fpexample/public  # fpexample 하위의 public 디렉토리를 배포
